# Numpy

In [ ]:
import numpy as np
m1=np.arange(1,13).reshape((3,4))
m1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
# IMPORTANT - Sacler Addition in numpy

m1+2

array([[ 3,  4,  5,  6],
       [ 7,  8,  9, 10],
       [11, 12, 13, 14]])

In [ ]:
# IMPORTANT - Conditional operators in Numpy

m1<6

array([[ True,  True,  True,  True],
       [ True, False, False, False],
       [False, False, False, False]])

In [ ]:
m1<6

array([[ True,  True,  True,  True],
       [ True, False, False, False],
       [False, False, False, False]])

In [ ]:
# IMPORTANT - Masking in Python

mask= m1<6
m1[mask]

array([1, 2, 3, 4, 5])

In [ ]:
mask2= (m1>6)
mask2

array([[False, False, False, False],
       [False, False,  True,  True],
       [ True,  True,  True,  True]])

In [ ]:
# Fancy Indexing
# gives me values based on the condition in the mask
m1[mask2]

array([ 7,  8,  9, 10, 11, 12])

In [ ]:

m1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
# IMPORTANT
# multiple conditions can be passed
# "|"" is used for "OR" and "&" is used as "AND"

mask3= ((m1<3) | (m1>6))
m1[mask3]

array([ 1,  2,  7,  8,  9, 10, 11, 12])

In [ ]:
mask3= ((m1<3) & (m1>6))
m1[mask3]

array([], dtype=int64)

In [ ]:
# Element wise addition
m1=m1+2

In [ ]:
m1

array([[ 3,  4,  5,  6],
       [ 7,  8,  9, 10],
       [11, 12, 13, 14]])

In [ ]:
m2=np.arange(1,13).reshape((3,4))

In [ ]:

m2[((m2<3) | (m2>6))]

array([ 1,  2,  7,  8,  9, 10, 11, 12])

In [ ]:
# IMPORTANT - Comparing two arrays

a=np.arange(1,13).reshape((3,4))
b=np.arange(1,13).reshape((3,4))
print(a)
print(b)

# checking whether all elements of a are equal to corresponding elements of b
print(a==b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]


In [ ]:
a=np.arange(1,13).reshape((3,4))
b=np.arange(1,13).reshape((2,6))
# print(a)
# print(b)

a==b

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:6: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  


False

In [ ]:
# IMPORTANT - Comparing two arrays

a = np.array([0,2,3])
b = np.array([1,3,5])
a>=b
# 2 arrays can be compared

array([False, False, False])

In [ ]:
m3=np.arange(1,13).reshape((3,4))
m3

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
# IMPORTANT - Replacing based on some condition
# replacing all the values less than 6 with 99 using masking
m3[m3<6]=99

In [ ]:
m3

array([[99, 99, 99, 99],
       [99,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
m4 =np.array([0,1,2,3,4,5])


In [ ]:
mask=(m4%2==0)
print(mask)


[ True False  True False  True False]


In [ ]:
m4[mask]=-1
print(m4)

[-1  1 -1  3 -1  5]


In [ ]:
# aggregate/universal functions

In [ ]:
a = np.array([0,2,3])
b = np.array([1,3,5])

a+b

array([1, 5, 8])

In [ ]:
# IMPORTANT - Aggregate functions in numpy array
# element wise sum of 3 arrays 
np.add(a,b)

array([1, 5, 8])

In [ ]:
# IMPORTANT - Aggregate functions in numpy array
np.divide(a,b)

array([0.        , 0.66666667, 0.6       ])

In [ ]:
n4=np.arange(1,13).reshape((3,4))
n5=np.arange(1,13).reshape((3,4))
print(n4)
print(n5)
np.add(n4,n5)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24]])

In [ ]:
n6=np.arange(1,13).reshape((3,4))
n6

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
# IMPORTANT
# returns sum of all the elements
np.sum(n6)

78

In [ ]:
# IMPORTANT
# returns sum across horizontal direction ( row wise summation)
np.sum(n6,axis=1)

array([10, 26, 42])

In [ ]:
# IMPORTANT
# returns sum across vertical direction ( column wise summation)
np.sum(n6,axis=0)

array([15, 18, 21, 24])

In [ ]:
# IMPORTANT
# np.sum(n6,axis=0)
n6.sum(axis=0)

array([15, 18, 21, 24])

In [ ]:
# IMPORTANT

np.sum(n6[0])

10

In [ ]:
# IMPORTANT

n6[:,0].sum()

15

In [ ]:
# IMPORTANT

np.sum(n6[:,0])

15

In [ ]:
# IMPORTANT

np.sum(n6[0])

10

In [ ]:
n6

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
# IMPORTANT

n6.sum(axis=0)

array([15, 18, 21, 24])

In [ ]:
# IMPORTANT

n6.sum(axis=1)

array([10, 26, 42])

In [ ]:
n7=np.arange(1,13).reshape((3,4))
n7

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
np.mean(n7,axis=1)

array([ 2.5,  6.5, 10.5])

In [ ]:
np.mean(n7,axis=0)

array([5., 6., 7., 8.])

In [ ]:
m7=np.arange(1,10).reshape((3,3))
m7

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
np.max(m7,axis=0)

array([7, 8, 9])

In [ ]:
np.max(m7,axis=1)

array([3, 6, 9])

In [ ]:
np.min(m7,axis=0)

array([1, 2, 3])

In [ ]:
np.min(m7,axis=1)

array([1, 4, 7])

In [ ]:
np.max(m7)

9

In [ ]:
# IMPORTANT

# Usage of np.any function
# returns True for atleast one non zero value
m8=np.array([0,0,1])
np.any(m8)

True

In [ ]:
m8=np.array([0,0,0])
np.any(m8)

False

In [ ]:
m8=np.array([True,False,False])
np.any(m8)

True

In [ ]:
a=np.array([1,2,3,4])
b=np.array([4,3,2,1])


In [ ]:
a<b

array([ True,  True, False, False])

In [ ]:
np.any(a<b)

True

In [ ]:
np.any([0,0,-1])

True

In [ ]:
a=np.array([[1, 2, 3],
 [4, 6, 6],
 [7, 8, 9]])

b=np.array([[1, 2, 3],
 [4, 5, 6],
 [7, 8, 9]])
# a>b
print(np.any(a>b))

True


In [ ]:
a=np.array([[1, 2, 3],
 [4, 6, 6],
 [7, 8, 9]])
print(a%2==0)
np.any(a%2==0)

[[False  True False]
 [ True  True  True]
 [False  True False]]


True

In [ ]:
# np.all()

In [ ]:
a=np.array([1,2,3,4])
b=np.array([4,3,2,1])
c=np.array([1,1,1,1])


In [ ]:
a<b

array([ True,  True, False, False])

In [ ]:
# IMPORTANT
# np.all 
# returns True only if all the elements are non zero

np.all(a<b)

False

In [ ]:
(a<b)|(a>c)


array([ True,  True,  True,  True])

In [ ]:
np.all((a<b)|(a>c))

True

In [ ]:
(a<b)&(a>c)

array([False,  True, False, False])

In [ ]:
m10=np.array([3,5,6,78,7,9,4])


In [ ]:
# IMPORTANT
# gives us sorted array
np.sort(m10)

array([ 3,  4,  5,  6,  7,  9, 78])

In [ ]:
# IMPORTANT
# returns list of indexes of elements in the original list after sorting.
np.argsort(m10)

array([0, 6, 1, 2, 4, 5, 3])

In [ ]:
m11=np.array([[10,4,3],[7,5,6],[9,8,7]])

In [ ]:
m11

array([[10,  4,  3],
       [ 7,  5,  6],
       [ 9,  8,  7]])

In [ ]:
# sorts the 2D array column wise
np.sort(m11,axis=0)

array([[ 7,  4,  3],
       [ 9,  5,  6],
       [10,  8,  7]])

In [ ]:
# sorts the 2D array row wise
np.sort(m11,axis=1)

array([[ 3,  4, 10],
       [ 5,  6,  7],
       [ 7,  8,  9]])

In [ ]:
np.sort(m11)

array([[ 3,  4, 10],
       [ 5,  6,  7],
       [ 7,  8,  9]])

In [ ]:
a = np.array([[23,4,43],
              [12,89,3],
              [69,420,0]])

b = np.sort(a)

In [ ]:
b

array([[  4,  23,  43],
       [  3,  12,  89],
       [  0,  69, 420]])

In [ ]:
a=np.array([[1, 2, 3],
 [4, 5, 6],
 [7, 8, 9]])

b=np.array([[1, 2, 3],
 [4, 5, 6],
 [7, 8, 9]])
print(a==b)
print(np.all(a==b))


[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
True


In [ ]:
# IMPORTANT
# Dataset Location - https://drive.google.com/file/d/1kXqcJo4YzmwF1G2BPoA17CI49TZVHANF/view

!gdown 1kXqcJo4YzmwF1G2BPoA17CI49TZVHANF

Downloading...
From: https://drive.google.com/uc?id=1kXqcJo4YzmwF1G2BPoA17CI49TZVHANF
To: /content/fitness.txt
100% 3.14k/3.14k [00:00<00:00, 4.18MB/s]


In [ ]:
# IMPORTANT
# Loading the data set
data=np.loadtxt("/content/fitness.txt",dtype='str')

In [ ]:
# glancing through the data
data

array([['06-10-2017', '5464', '200', '181', '5', '0', '66'],
       ['07-10-2017', '6041', '100', '197', '8', '0', '66'],
       ['08-10-2017', '25', '100', '0', '5', '0', '66'],
       ['09-10-2017', '5461', '100', '174', '4', '0', '66'],
       ['10-10-2017', '6915', '200', '223', '5', '500', '66'],
       ['11-10-2017', '4545', '100', '149', '6', '0', '66'],
       ['12-10-2017', '4340', '100', '140', '6', '0', '66'],
       ['13-10-2017', '1230', '100', '38', '7', '0', '66'],
       ['14-10-2017', '61', '100', '1', '5', '0', '66'],
       ['15-10-2017', '1258', '100', '40', '6', '0', '65'],
       ['16-10-2017', '3148', '100', '101', '8', '0', '65'],
       ['17-10-2017', '4687', '100', '152', '5', '0', '65'],
       ['18-10-2017', '4732', '300', '150', '6', '500', '65'],
       ['19-10-2017', '3519', '100', '113', '7', '0', '65'],
       ['20-10-2017', '1580', '100', '49', '5', '0', '65'],
       ['21-10-2017', '2822', '100', '86', '6', '0', '65'],
       ['22-10-2017', '181', '10

In [ ]:
# printing out the first 5 rows
data[:5]

array([['06-10-2017', '5464', '200', '181', '5', '0', '66'],
       ['07-10-2017', '6041', '100', '197', '8', '0', '66'],
       ['08-10-2017', '25', '100', '0', '5', '0', '66'],
       ['09-10-2017', '5461', '100', '174', '4', '0', '66'],
       ['10-10-2017', '6915', '200', '223', '5', '500', '66']],
      dtype='<U10')

In [ ]:
# date,step_count,mood,calories_burned,sleep_hours,activity_status,weight

In [ ]:
data[0]

array(['06-10-2017', '5464', '200', '181', '5', '0', '66'], dtype='<U10')

In [ ]:
# data

In [ ]:
# taking transpose of data to get one feature in one row.
data=data.T

In [ ]:
data

array([['06-10-2017', '07-10-2017', '08-10-2017', '09-10-2017',
        '10-10-2017', '11-10-2017', '12-10-2017', '13-10-2017',
        '14-10-2017', '15-10-2017', '16-10-2017', '17-10-2017',
        '18-10-2017', '19-10-2017', '20-10-2017', '21-10-2017',
        '22-10-2017', '23-10-2017', '24-10-2017', '25-10-2017',
        '26-10-2017', '27-10-2017', '28-10-2017', '29-10-2017',
        '30-10-2017', '31-10-2017', '01-11-2017', '02-11-2017',
        '03-11-2017', '04-11-2017', '05-11-2017', '06-11-2017',
        '07-11-2017', '08-11-2017', '09-11-2017', '10-11-2017',
        '11-11-2017', '12-11-2017', '13-11-2017', '14-11-2017',
        '15-11-2017', '16-11-2017', '17-11-2017', '18-11-2017',
        '19-11-2017', '20-11-2017', '21-11-2017', '22-11-2017',
        '23-11-2017', '24-11-2017', '25-11-2017', '26-11-2017',
        '27-11-2017', '28-11-2017', '29-11-2017', '30-11-2017',
        '01-12-2017', '02-12-2017', '03-12-2017', '04-12-2017',
        '05-12-2017', '06-12-2017', '07-

In [ ]:
data[0]

array(['06-10-2017', '07-10-2017', '08-10-2017', '09-10-2017',
       '10-10-2017', '11-10-2017', '12-10-2017', '13-10-2017',
       '14-10-2017', '15-10-2017', '16-10-2017', '17-10-2017',
       '18-10-2017', '19-10-2017', '20-10-2017', '21-10-2017',
       '22-10-2017', '23-10-2017', '24-10-2017', '25-10-2017',
       '26-10-2017', '27-10-2017', '28-10-2017', '29-10-2017',
       '30-10-2017', '31-10-2017', '01-11-2017', '02-11-2017',
       '03-11-2017', '04-11-2017', '05-11-2017', '06-11-2017',
       '07-11-2017', '08-11-2017', '09-11-2017', '10-11-2017',
       '11-11-2017', '12-11-2017', '13-11-2017', '14-11-2017',
       '15-11-2017', '16-11-2017', '17-11-2017', '18-11-2017',
       '19-11-2017', '20-11-2017', '21-11-2017', '22-11-2017',
       '23-11-2017', '24-11-2017', '25-11-2017', '26-11-2017',
       '27-11-2017', '28-11-2017', '29-11-2017', '30-11-2017',
       '01-12-2017', '02-12-2017', '03-12-2017', '04-12-2017',
       '05-12-2017', '06-12-2017', '07-12-2017', '08-12

In [ ]:
# unpacking and assigning feature(column) names
# date,step_count,mood,calories_burned,sleep_hours,activity_status,weight=data
date=data[0]
step_count=data[1]
mood=data[2]
calories_burned=data[3]
sleep_hours=data[4]
activity_status=data[5]
weight=data[6]

In [ ]:

step_count

array(['5464', '6041', '25', '5461', '6915', '4545', '4340', '1230', '61',
       '1258', '3148', '4687', '4732', '3519', '1580', '2822', '181',
       '3158', '4383', '3881', '4037', '202', '292', '330', '2209',
       '4550', '4435', '4779', '1831', '2255', '539', '5464', '6041',
       '4068', '4683', '4033', '6314', '614', '3149', '4005', '4880',
       '4136', '705', '570', '269', '4275', '5999', '4421', '6930',
       '5195', '546', '493', '995', '1163', '6676', '3608', '774', '1421',
       '4064', '2725', '5934', '1867', '3721', '2374', '2909', '1648',
       '799', '7102', '3941', '7422', '437', '1231', '1696', '4921',
       '221', '6500', '3575', '4061', '651', '753', '518', '5537', '4108',
       '5376', '3066', '177', '36', '299', '1447', '2599', '702', '133',
       '153', '500', '2127', '2203'], dtype='<U10')

In [ ]:
# data[0]

In [ ]:
#converting string dtype to int64 dtype
step_count=np.array(step_count,dtype="int64")
step_count

array([5464, 6041,   25, 5461, 6915, 4545, 4340, 1230,   61, 1258, 3148,
       4687, 4732, 3519, 1580, 2822,  181, 3158, 4383, 3881, 4037,  202,
        292,  330, 2209, 4550, 4435, 4779, 1831, 2255,  539, 5464, 6041,
       4068, 4683, 4033, 6314,  614, 3149, 4005, 4880, 4136,  705,  570,
        269, 4275, 5999, 4421, 6930, 5195,  546,  493,  995, 1163, 6676,
       3608,  774, 1421, 4064, 2725, 5934, 1867, 3721, 2374, 2909, 1648,
        799, 7102, 3941, 7422,  437, 1231, 1696, 4921,  221, 6500, 3575,
       4061,  651,  753,  518, 5537, 4108, 5376, 3066,  177,   36,  299,
       1447, 2599,  702,  133,  153,  500, 2127, 2203])

In [ ]:
calories_burned=np.array(calories_burned,dtype="int64")
calories_burned


array([181, 197,   0, 174, 223, 149, 140,  38,   1,  40, 101, 152, 150,
       113,  49,  86,   6,  99, 143, 125, 129,   6,   9,  10,  72, 150,
       141, 156,  57,  72,  17, 181, 197, 131, 154, 137, 193,  19, 101,
       139, 164, 137,  22,  17,   9, 145, 192, 146, 234, 167,  16,  17,
        32,  35, 220, 116,  23,  44, 131,  86, 194,  60, 121,  76,  93,
        53,  25, 227, 125, 243,  14,  39,  55, 158,   7, 213, 116, 129,
        21,  28,  16, 180, 138, 176,  99,   5,   1,  10,  47,  84,  23,
         4,   0,   0,   0,   0])

In [ ]:
sleep_hours=np.array(sleep_hours,dtype="int64")
sleep_hours

array([5, 8, 5, 4, 5, 6, 6, 7, 5, 6, 8, 5, 6, 7, 5, 6, 8, 5, 4, 5, 6, 8,
       5, 6, 5, 8, 5, 4, 5, 4, 5, 4, 3, 2, 9, 5, 6, 4, 5, 8, 4, 5, 6, 5,
       6, 5, 6, 5, 6, 5, 6, 7, 6, 7, 6, 5, 6, 7, 8, 8, 7, 8, 5, 4, 3, 3,
       4, 5, 5, 5, 3, 4, 4, 5, 5, 5, 5, 5, 5, 4, 3, 4, 5, 5, 4, 5, 3, 3,
       3, 2, 3, 2, 8, 5, 5, 5])

In [ ]:
weight=np.array(weight,dtype="int64")
weight

array([66, 66, 66, 66, 66, 66, 66, 66, 66, 65, 65, 65, 65, 65, 65, 65, 65,
       65, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64,
       64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64,
       64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64,
       64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64,
       64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64])

In [ ]:
mood

array(['200', '100', '100', '100', '200', '100', '100', '100', '100',
       '100', '100', '100', '300', '100', '100', '100', '100', '200',
       '200', '200', '200', '200', '200', '300', '200', '300', '300',
       '300', '300', '300', '300', '300', '200', '300', '300', '300',
       '300', '300', '300', '300', '300', '300', '300', '200', '300',
       '300', '300', '300', '300', '300', '300', '300', '300', '200',
       '100', '300', '300', '300', '300', '300', '300', '300', '100',
       '200', '200', '100', '100', '200', '200', '300', '200', '200',
       '100', '200', '100', '200', '200', '100', '100', '100', '100',
       '300', '200', '300', '200', '100', '100', '100', '200', '200',
       '100', '100', '300', '200', '200', '300'], dtype='<U10')

In [ ]:
# Using masking , we are converting string values into understable form
mood[mood=='100']='sad'
mood[mood=='200']='neutral'
mood[mood=='300']='happy'

In [ ]:

mood


array(['neutral', 'sad', 'sad', 'sad', 'neutral', 'sad', 'sad', 'sad',
       'sad', 'sad', 'sad', 'sad', 'happy', 'sad', 'sad', 'sad', 'sad',
       'neutral', 'neutral', 'neutral', 'neutral', 'neutral', 'neutral',
       'happy', 'neutral', 'happy', 'happy', 'happy', 'happy', 'happy',
       'happy', 'happy', 'neutral', 'happy', 'happy', 'happy', 'happy',
       'happy', 'happy', 'happy', 'happy', 'happy', 'happy', 'neutral',
       'happy', 'happy', 'happy', 'happy', 'happy', 'happy', 'happy',
       'happy', 'happy', 'neutral', 'sad', 'happy', 'happy', 'happy',
       'happy', 'happy', 'happy', 'happy', 'sad', 'neutral', 'neutral',
       'sad', 'sad', 'neutral', 'neutral', 'happy', 'neutral', 'neutral',
       'sad', 'neutral', 'sad', 'neutral', 'neutral', 'sad', 'sad', 'sad',
       'sad', 'happy', 'neutral', 'happy', 'neutral', 'sad', 'sad', 'sad',
       'neutral', 'neutral', 'sad', 'sad', 'happy', 'neutral', 'neutral',
       'happy'], dtype='<U10')

In [ ]:
activity_status

array(['0', '0', '0', '0', '500', '0', '0', '0', '0', '0', '0', '0',
       '500', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0',
       '500', '0', '0', '0', '0', '500', '0', '0', '0', '0', '0', '500',
       '500', '500', '500', '500', '500', '500', '500', '500', '0', '0',
       '0', '0', '0', '0', '500', '500', '500', '500', '500', '500',
       '500', '500', '500', '500', '500', '500', '0', '500', '500', '0',
       '500', '500', '500', '500', '500', '0', '500', '500', '500', '500',
       '0', '0', '0', '0', '500', '500', '500', '500', '0', '0', '0', '0',
       '0', '0', '0', '0', '500', '0', '500'], dtype='<U10')

In [ ]:

activity_status[activity_status=='0']='Inactive'
activity_status[activity_status=='500']='Active'
activity_status

array(['Inactive', 'Inactive', 'Inactive', 'Inactive', 'Active',
       'Inactive', 'Inactive', 'Inactive', 'Inactive', 'Inactive',
       'Inactive', 'Inactive', 'Active', 'Inactive', 'Inactive',
       'Inactive', 'Inactive', 'Inactive', 'Inactive', 'Inactive',
       'Inactive', 'Inactive', 'Inactive', 'Inactive', 'Inactive',
       'Active', 'Inactive', 'Inactive', 'Inactive', 'Inactive', 'Active',
       'Inactive', 'Inactive', 'Inactive', 'Inactive', 'Inactive',
       'Active', 'Active', 'Active', 'Active', 'Active', 'Active',
       'Active', 'Active', 'Active', 'Inactive', 'Inactive', 'Inactive',
       'Inactive', 'Inactive', 'Inactive', 'Active', 'Active', 'Active',
       'Active', 'Active', 'Active', 'Active', 'Active', 'Active',
       'Active', 'Active', 'Active', 'Inactive', 'Active', 'Active',
       'Inactive', 'Active', 'Active', 'Active', 'Active', 'Active',
       'Inactive', 'Active', 'Active', 'Active', 'Active', 'Inactive',
       'Inactive', 'Inactive', 'Inacti

In [ ]:
# gives me unique values in numpy array 
# return_count gives me frequency of each unique value
np.unique(activity_status,return_counts=True)

(array(['Active', 'Inactive'], dtype='<U10'), array([42, 54]))

In [ ]:
np.unique(mood,return_counts=True)

(array(['happy', 'neutral', 'sad'], dtype='<U10'), array([40, 27, 29]))

In [ ]:
np.unique(sleep_hours,return_counts=True)

(array([2, 3, 4, 5, 6, 7, 8, 9]), array([ 3,  9, 14, 37, 16,  6, 10,  1]))

In [ ]:
np.unique(mood)

array(['happy', 'neutral', 'sad'], dtype='<U10')

In [ ]:
# finding out average number of steps that person takes
step_count.mean()

2935.9375

In [ ]:
step_count

array([5464, 6041,   25, 5461, 6915, 4545, 4340, 1230,   61, 1258, 3148,
       4687, 4732, 3519, 1580, 2822,  181, 3158, 4383, 3881, 4037,  202,
        292,  330, 2209, 4550, 4435, 4779, 1831, 2255,  539, 5464, 6041,
       4068, 4683, 4033, 6314,  614, 3149, 4005, 4880, 4136,  705,  570,
        269, 4275, 5999, 4421, 6930, 5195,  546,  493,  995, 1163, 6676,
       3608,  774, 1421, 4064, 2725, 5934, 1867, 3721, 2374, 2909, 1648,
        799, 7102, 3941, 7422,  437, 1231, 1696, 4921,  221, 6500, 3575,
       4061,  651,  753,  518, 5537, 4108, 5376, 3066,  177,   36,  299,
       1447, 2599,  702,  133,  153,  500, 2127, 2203])

In [ ]:
step_count

array([5464, 6041,   25, 5461, 6915, 4545, 4340, 1230,   61, 1258, 3148,
       4687, 4732, 3519, 1580, 2822,  181, 3158, 4383, 3881, 4037,  202,
        292,  330, 2209, 4550, 4435, 4779, 1831, 2255,  539, 5464, 6041,
       4068, 4683, 4033, 6314,  614, 3149, 4005, 4880, 4136,  705,  570,
        269, 4275, 5999, 4421, 6930, 5195,  546,  493,  995, 1163, 6676,
       3608,  774, 1421, 4064, 2725, 5934, 1867, 3721, 2374, 2909, 1648,
        799, 7102, 3941, 7422,  437, 1231, 1696, 4921,  221, 6500, 3575,
       4061,  651,  753,  518, 5537, 4108, 5376, 3066,  177,   36,  299,
       1447, 2599,  702,  133,  153,  500, 2127, 2203])

In [ ]:
np.mean(step_count)

2935.9375

In [ ]:
# gives me max number of steps taken
np.max(step_count)

7422

In [ ]:
# return index of max value of step count
np.argmax(step_count)

69

In [ ]:
# using masking we are able to find out the date on which that person took max no. of steps
date[np.argmax(step_count)]

'14-12-2017'

In [ ]:
# using masking we are able to find out the calories burned for max steps taken
calories_burned[np.argmax(step_count)]

243

In [ ]:
# using masking we are able to find out the mood on that day on which he took max no. of steps
mood[np.argmax(step_count)]

'happy'

In [ ]:
calories_burned[np.argmin(step_count)]

0

In [ ]:
mood[np.argmin(step_count)]

'sad'

In [ ]:
step_count[np.argmin(step_count)]

25

In [ ]:
# finding out average of steps that person takes on days when he sad
np.mean(step_count[mood=='sad'])

2103.0689655172414

In [ ]:
# finding out average of steps that person takes on days when he happy
np.mean(step_count[mood=='happy'])

3392.725

In [ ]:
# finding out average of steps that person takes on days when he neutral
np.mean(step_count[mood=='neutral'])

3153.777777777778

In [ ]:
# finding out the freq of that person's mood for all the days he walked for more than 4000 steps
np.unique(mood[step_count>4000],return_counts=True)

(array(['happy', 'neutral', 'sad'], dtype='<U10'), array([22,  9,  7]))

In [ ]:
# finding out the freq of that person's mood for all the days he walked for less than 2000 steps
np.unique(mood[step_count<2000],return_counts=True)

(array(['happy', 'neutral', 'sad'], dtype='<U10'), array([13,  8, 18]))

In [ ]:
sleep_hours

array([5, 8, 5, 4, 5, 6, 6, 7, 5, 6, 8, 5, 6, 7, 5, 6, 8, 5, 4, 5, 6, 8,
       5, 6, 5, 8, 5, 4, 5, 4, 5, 4, 3, 2, 9, 5, 6, 4, 5, 8, 4, 5, 6, 5,
       6, 5, 6, 5, 6, 5, 6, 7, 6, 7, 6, 5, 6, 7, 8, 8, 7, 8, 5, 4, 3, 3,
       4, 5, 5, 5, 3, 4, 4, 5, 5, 5, 5, 5, 5, 4, 3, 4, 5, 5, 4, 5, 3, 3,
       3, 2, 3, 2, 8, 5, 5, 5])

In [ ]:
# finding out freq of mood for the days where that person slept for more than 5 hours
np.unique(mood[sleep_hours>5],return_counts=True)

(array(['happy', 'neutral', 'sad'], dtype='<U10'), array([20,  3, 10]))

In [ ]:
mood[np.argmax(step_count)]

'happy'

In [ ]:
#average sleep hours

print(np.mean(sleep_hours))

5.21875


In [ ]:
# Sleep Hours has no impact on activity status
np.unique(activity_status[sleep_hours>=5],return_counts=True)

(array(['Active', 'Inactive'], dtype='<U10'), array([34, 36]))

In [ ]:
# Sleep Hours has no impact on activity status
np.unique(activity_status[sleep_hours>=6],return_counts=True)

(array(['Active', 'Inactive'], dtype='<U10'), array([16, 17]))

In [ ]:
# Sleep Hours has no impact on activity status
np.unique(activity_status[sleep_hours>=7],return_counts=True)

(array(['Active', 'Inactive'], dtype='<U10'), array([9, 8]))

In [ ]:
# Burns more calories when he is 'happy'/'neutral' as compared to being 'sad'
print(np.mean(calories_burned[mood == 'happy']))
print(np.mean(calories_burned[mood == 'neutral']))
print(np.mean(calories_burned[mood == 'sad']))

108.55
98.70370370370371
67.72413793103448


In [ ]:
# He is expected to be more 'happy'/'neutral' when is 'Active', whereas he is more 'sad' when is 'Inactive'

print(np.unique(mood[activity_status=='Active'], return_counts=True))

print(np.unique(mood[activity_status=='Inactive'], return_counts=True))

(array(['happy', 'neutral', 'sad'], dtype='<U10'), array([24, 14,  4]))
(array(['happy', 'neutral', 'sad'], dtype='<U10'), array([16, 13, 25]))


In [ ]:
# No impact on weight due to activity status

print(np.unique(weight[activity_status=='Active'], return_counts=True))
print(np.unique(weight[activity_status=='Inactive'], return_counts=True))

(array([64, 65, 66]), array([40,  1,  1]))
(array([64, 65, 66]), array([38,  8,  8]))


In [ ]:
# No impact on weight due to mood

print(np.unique(weight[mood=='happy'], return_counts=True))
print(np.unique(weight[mood=='neutral'], return_counts=True))
print(np.unique(weight[mood=='sad'], return_counts=True))

(array([64, 65]), array([39,  1]))
(array([64, 65, 66]), array([24,  1,  2]))
(array([64, 65, 66]), array([15,  7,  7]))


#Assignment

In [ ]:
# Question No.4

import numpy as np

arr = np.array([1,3,4,1,2])
result = np.zeros((arr.size, max(arr)+1))
print(result)

for i in range(0, len(arr)):
  result[i,arr[i]] = 1

print(result)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


In [ ]:
# Question No.6

mat1 = np.array([[6, 6, 4, 7, 9],
 [0, 2, 2, 9, 3],
 [6, 0, 2, 5, 2],
 [2, 4, 3, 5, 5]])
mat2 = np.array([[8, 6, 6, 8, 3],
 [2, 7, 0, 3, 1],
 [3, 2, 1, 5, 2],
 [7, 0, 7, 6, 8],
 [1, 5, 6, 4, 5]])
r1, r2 = 1, 3
c1, c2 = 2, 4

np.dot(mat1, mat2)

array([[130, 131, 143, 164, 133],
       [ 76,  33,  83,  82,  93],
       [ 91,  50,  85,  96,  72],
       [ 73,  71,  80,  93,  81]])

In [ ]:
mat1 = np.array([[1,2,3],[1,2,3]])
mat2 = np.array([[1,2],[3,4],[5,6]])
r1, r2 = 0, 4
c1, c2 = 0, 1

np.dot(mat1, mat2)

array([[22, 28],
       [22, 28]])

In [ ]:
# Question 7
import numpy as np
arr = np.array([[2,3,4],
               [5,6,7]])

print(len(arr))
print(len(arr[0]))
print(arr)



2
3
[[2 3 4]
 [5 6 7]]


In [ ]:
for i in range(0, len(arr)):
  for j in range(0, len(arr[i])):
    val = arr[i,j]
    print(val)

2
3
4
5
6
7


In [ ]:
val = 7
str1 = ''
rem = None
while val != 0:
  rem = val%2
  str1 = str(rem) + str1
  val = val//2

print(str1)

111


In [ ]:
for i in range(0, len(arr)):
  for j in range(0, len(arr[i])):
    val = arr[i,j]
    str1 = ''
    rem = None
    while val != 0:
      rem = val%2
      str1 = str(rem) + str1
      val = val//2
    arr[i,j] = int(str1)

arr

array([[ 10,  11, 100],
       [101, 110, 111]])

### Doubts

In [ ]:
m1=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(m1.ndim)

2


In [ ]:
m1.shape

(3, 3)

In [ ]:
np.min(step_count)

25

In [ ]:
x = np.ones((5,5))
x[1:-1,1:-1] = 0
x

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
m11=np.arange(1,13).reshape((3,4))

In [ ]:
m11

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
# a[::-1] vs a[0::-1] vs a[:0:-1s]

In [ ]:
a=np.arange(1,13)

In [ ]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
a[::-1]

array([12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [ ]:
a[0::-1]

array([1])

In [ ]:
a[:0:-1]

array([12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2])

In [ ]:
a = np.array([[23,4,43],
              [12,89,3],
              [69,420,0]])


In [ ]:
a[0::-1,:]

array([[23,  4, 43]])

In [ ]:
a=np.arange(1,13)
a


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
a[0::-1]

array([1])

In [ ]:
a[3::-1]

array([4, 3, 2, 1])

In [ ]:
a[:0:-1]

array([12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2])

In [ ]:
a = np.array([[23,4,43],
              [12,89,3],
              [69,420,0]])

In [ ]:
a[::-1]

array([[ 69, 420,   0],
       [ 12,  89,   3],
       [ 23,   4,  43]])