In [ ]:
print("Welcome to Numpy - 1")

Welcome to Numpy - 1


In [ ]:
!pip install numpy # installing  numpy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
import numpy as np # importing numpy

In [ ]:
a=[1,2,3,4,5]

In [ ]:
a

[1, 2, 3, 4, 5]

In [ ]:
[i*2 for i in a]

[2, 4, 6, 8, 10]

In [ ]:
# IMPORTANT - Multiplication

b=np.array([1,2,3,4,5])
print(b*2)

[ 2  4  6  8 10]


In [ ]:
l=range(10000)


In [ ]:
# IMPORTANT - Time taken to execute a list 10000 times

%timeit [i*2 for i in l] 

757 µs ± 8.58 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [ ]:
l=np.arange(10000)


In [ ]:
# IMPORTANT - Time taken to execute a numpy array 10000 times

%timeit l*2

6.48 µs ± 98.2 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [ ]:
a=np.array([1,2,3,4,5])

In [ ]:
print(a)

[1 2 3 4 5]


In [ ]:
a.ndim # gives us the dimensions of the numpy array

1

In [ ]:
a.shape # gives us the shape of the numpy array

(5,)

In [ ]:
a=np.array([1,2,3,4,5,6,7,8])
a.ndim

1

In [ ]:
a.shape

(8,)

In [ ]:
m= np.arange(1,10) # arange function in Numpy is very similar to range function
                    #np.arange(start,stop,step)
print(m)

[1 2 3 4 5 6 7 8 9]


In [ ]:
# IMPORTANT - Step size in np.arange() function

m= np.arange(1,10,2)
print(m)

[1 3 5 7 9]


In [ ]:
# IMPORTANT - Step sizes in np.arange() function

#one difference from range function
# we can provide floats in steps size in np.arange()
m= np.arange(1,10,0.5) 
print(m)

[1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5 9.  9.5]


In [ ]:
# creates equally spaced numbers 
# np.linspace(start,stop(included),total No. of values we want)
print(np.linspace(0,100,25))

[  0.           4.16666667   8.33333333  12.5         16.66666667
  20.83333333  25.          29.16666667  33.33333333  37.5
  41.66666667  45.83333333  50.          54.16666667  58.33333333
  62.5         66.66666667  70.83333333  75.          79.16666667
  83.33333333  87.5         91.66666667  95.83333333 100.        ]


In [ ]:
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [ ]:
a=np.array([1,2,3,4,5,6,7,8])

In [ ]:
# tells me the type of entire array
type(a)

numpy.ndarray

In [ ]:
# tells me the data type of elements in numpy array
a.dtype

dtype('int64')

In [ ]:
# IMPORTANT - Conversion in Numpy Array

a=np.array([1,2,3,4,5,6,7,7.5])
print(a)

[1.  2.  3.  4.  5.  6.  7.  7.5]


In [ ]:
a.dtype

dtype('float64')

In [ ]:
# IMPORTANT - Numpy Array is homogenous, list is heterogenous

a=np.array([1,2,3,4,5,6,7,'7.5',4.5])
print(a)

['1' '2' '3' '4' '5' '6' '7' '7.5' '4.5']


In [ ]:
a.dtype

dtype('<U32')

In [ ]:
# IMPORTANT - Numpy Array is homogenous, list is heterogenous

a=np.array([1,2,3,4,5,6,7],dtype="float64")
print(a)
print(a.dtype)

[1. 2. 3. 4. 5. 6. 7.]
float64


In [ ]:
# IMPORTANT - Numpy Array is homogenous, list is heterogenous

a=np.array([1,2,3,4,5,6,7.5],dtype="int64")
print(a)
print(a.dtype)

[1 2 3 4 5 6 7]
int64


In [ ]:
100**10

100000000000000000000

In [ ]:
b=np.array([100])
b**10

array([7766279631452241920])

In [ ]:
m1=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(m1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
m1.ndim

2

In [ ]:
m1.shape

(3, 3)

In [ ]:
# len() gives me the value in first dimension
len(m1)

3

In [ ]:
m2=np.arange(1,13)
print(m2)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [ ]:
# IMPORTANT

# reshape is used to change the shapes of numpy arrays
m2.reshape((3,4))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
m2.reshape((4,3))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
m2.reshape((2,6))

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [ ]:
m2.reshape((6,2))

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [ ]:
# IMPORTANT
# we can pass "-1" whenever we are not sure about the value in that dimension.
m2.reshape((2,-1))

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [ ]:
# IMPORTANT - Number of elements in the array should be a multiple of both N rows and M columns for reshaping an array

m2.reshape((-1,5))

ValueError: ignored

In [ ]:
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
m3=np.arange(1,17).reshape(-1,2)
print(m3)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]]


In [ ]:
m3.shape

(8, 2)

In [ ]:
m3=m3.reshape(2,8)

In [ ]:
m2=np.arange(1,13)
print(m2)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [ ]:
m2=m2.reshape(3,4)

In [ ]:
print(m2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
m2=np.arange(1,13)
print(m2)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [ ]:
m2.shape

(12,)

In [ ]:
m2.reshape(12,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [ ]:
m2.reshape(1,12)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [ ]:
m2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
m5=np.arange(1,13).reshape(3,4)
print(m5)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
# "numpy_array".T gives me a transpose
# transpose means changing rows to columns and columns to rows
# rows --> columns , columns --> rows
m6=m5.T
m6.shape

(4, 3)

In [ ]:
m2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
m2.T

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
m7=m2.reshape(1,12)

In [ ]:
m7

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [ ]:
m8=m7.T
print(m8)

[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]]


In [ ]:
m8.shape

(12, 1)

In [ ]:
m5=np.arange(1,13).reshape(3,4)
print(m5)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
# IMPORTANT - Convert 2d array to one d array

m8=m5.flatten()
print(m8)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [ ]:
m8.shape

(12,)

In [ ]:
m5=np.arange(1,10).reshape(3,3)
print(m5)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
m5=np.arange(1,10).reshape(3,3)
print(m5)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
m5[0][1]

2

In [ ]:
m5[0,1]

2

In [ ]:
# special array 
# creating array where all the values are 0
# notice the dimension part in this example and the next
# always returns floats
np.zeros(3)

array([0., 0., 0.])

In [ ]:
# IMPORTANT - By default the format is float

np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
# IMPORTANT - Conversion to int type

np.zeros((3,3), dtype = 'int64')

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [ ]:
# IMPORTANT
# special array 
# creating array where all the values are 1
# always returns floats
n=np.ones((3,4))
print(n)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
# IMPORTANT

# using np.ones we can create any array by multiplying it with that number
n*2

array([[2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.]])

In [ ]:
n*10

array([[10., 10., 10., 10.],
       [10., 10., 10., 10.],
       [10., 10., 10., 10.]])

In [ ]:
# IMPORTANT

# another way of creating array and filling in with desired value.
# always returns integers by default , need to pass floats specifically
np.full((3,4),2)

array([[2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2]])

In [ ]:
# IMPORTANT

np.full((3,3),5.0)

array([[5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.]])

In [ ]:
# IMPORTANT

# np.diag will give us an arary where the diagonal matrix will have values and the rest 0
np.diag([1,2,3,4])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [ ]:
# gives me an identity matrix
# since the identity matrix is KxK
# we only need to provide one parameter
n1=np.identity(5)
n1

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
n1.dtype

dtype('float64')

In [ ]:
n1*4

array([[4., 0., 0., 0., 0.],
       [0., 4., 0., 0., 0.],
       [0., 0., 4., 0., 0.],
       [0., 0., 0., 4., 0.],
       [0., 0., 0., 0., 4.]])

In [ ]:
m5=np.arange(1,10).reshape(3,3)
print(m5)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
# accessing elements in 2D array method 1
m5[0][1]

2

In [ ]:
# accessing elements in 2D array method 2 
m5[0,1]

2

In [ ]:
#cannot access elements for which index is not present
m5[3,3]

IndexError: ignored

In [ ]:
n3=np.array([1,2,3,4,5,6,7,8,9])


In [ ]:
# we can pass in the list of indexes and fetch the values directly
n3[[1,3,5,7,7]]

array([2, 4, 6, 8, 8])

In [ ]:
n3[[1,3,5,7,7]]

array([2, 4, 6, 8, 8])

In [ ]:
n4=np.arange(1,10).reshape(3,3)

In [ ]:
n4

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
# For 2D array we pass 2 lists of corresponding row and column indexes for each value that we want
n4[[1,2,0,0],[0,1,2,0]]

array([4, 8, 3, 1])

In [ ]:
n5=np.arange(12)
n5

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
# slicing
n5[:5]

array([0, 1, 2, 3, 4])

In [ ]:
n6=np.arange(1,10).reshape(3,3)
n6

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
n6[:2,:]

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
n6[:,:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [ ]:
# slicing with step size
n6[:,::2]

array([[1, 3],
       [4, 6],
       [7, 9]])

In [ ]:
# Using specific column indexes that we want
# notice that we have passed in the indexes in tuple 
n6[:,(0,2)]

array([[1, 3],
       [4, 6],
       [7, 9]])

In [ ]:
n6[1,:2]

array([4, 5])

In [ ]:
n7=np.arange(12).reshape(3,4)
n7

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
n7[0,1:3]

array([1, 2])

In [ ]:
# assignment 
# we are assigning values here 
n7[0,0]=99
print(n7)

[[99  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
n8=np.arange(12)
n8

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
# assigning multiple values
n8[:3]=10,20,30

In [ ]:
n8

array([10, 20, 30,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
n8=np.arange(6)
n8[:3]=10,20,13

In [ ]:
n8

array([10, 20, 13,  3,  4,  5])

In [ ]:
a=[1,2,3,4,5]
b=[8,7,6]


In [ ]:
b[::-1]

[6, 7, 8]

In [ ]:
a[2:]=b[::-1]

In [ ]:
m=np.arange(1,6)
print(m)

[1 2 3 4 5]


In [ ]:
np.arange(1,6)

array([1, 2, 3, 4, 5])

In [ ]:
n8=np.arange(6)
print(n8)
n8[:3]=10,20,13

[0 1 2 3 4 5]


In [ ]:
n8

array([10, 20, 13,  3,  4,  5])

In [ ]:
n6=np.arange(1,10).reshape(3,3)
n6

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
n6[:,:]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
n6[:,1:]

array([[2, 3],
       [5, 6],
       [8, 9]])

In [ ]:
n6[2:,2:]

array([[9]])